easy_admin:
  entities:
    # List the entity class name you want to manage

    Article:
      class: App\Entity\Article
      form:
        fields:
          # ...
          - { property: "titre", type: "text" }
          - { property: "introduction", type: "textarea" }
          - { property: "contenu", type: "fos_ckeditor" }
          - { property: "createdAt", type: "date" }
          - { property: "thumbnailFile", type: "vich_image" }
      list:
        fields: ["titre", "createdAt", "introduction"]
    Comment:
      class: App\Entity\Comment
    Category:
      class: App\Entity\Category
  design:
    form_theme:
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
