easy_admin:
  entities:
    # List the entity class name you want to manage

    Article:
      class: App\Entity\Article
      form:
        fields:
          # ...
          - { property: "titre", type: "text" }
          - { property: "introduction", type: "textarea" }
          - { property: "contenu", type: "fos_ckeditor" }
          - { property: "createdAt", type: "datetime" }
          - { property: "note", type: "text" }
          - {
              property: "language",
              label: "Langue",
              type: "choice",
              type_options:
                {
                  multiple: false,
                  choices: { "Français": "fr", "Anglais": "en" },
                },
            }
          - { property: "thumbnailFile", type: "vich_image" }
      list:
        fields: ["titre", "createdAt", "introduction", "language"]

  design:
    form_theme:
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
